Добавили поиск в ширину
quorus-environment/urfu-navigation pull request #14
Opened 2022-11-21 04:51 UTC by Gribanov-Danil

2022-11-23 18:50 UTC, EgorKobelev approved these changes

2022-11-24 09:36 UTC, Konstaphy requested changes

2022-11-24 09:36 UTC, Konstaphy commented on BreadthSearch.ts
> +}
у нас есть тип граф, использовать его

2022-11-24 09:36 UTC, Konstaphy commented on BreadthSearch.ts
> +
тс кастит без явного указания типа, можно убрать все что между названием и знаком =

2022-11-24 09:36 UTC, Konstaphy commented on BreadthSearch.ts
> +function GetResultRoute(startPointID: string, endPointID: string): Array<string> {
функции с маленькой буквы начинаются

2022-11-24 09:36 UTC, Konstaphy commented on BreadthSearch.ts
> +function BreadthSearch(graph: Array<Node>, startPointID: string, endPointID: string): Array<string> {
таакже

2022-11-24 09:36 UTC, Konstaphy commented on BreadthSearch.ts
> +function Initialization(graph: Array<Node>, startPointID: string, endPointID: string) {
тоже

2022-11-24 09:36 UTC, Konstaphy commented on BreadthSearch.ts
> +function Initialization(graph: Array<Node>, startPointID: string, endPointID: string) {
также название не отражает суть

2022-12-03 09:36 UTC, closed without merging