Feature/UI kit
quorus-environment/urfu-navigation pull request #20
Opened 2022-12-07 19:07 UTC by OvechkinDmitry

2022-12-08 15:23 UTC, Konstaphy requested changes

2022-12-08 15:23 UTC, Konstaphy commented on src/shared/ordinarySearch/ordinarySearch.tsx
> +  {
а зачем тут тесты

2022-12-08 15:23 UTC, Konstaphy commented on src/shared/ordinarySearch/ordinarySearch.tsx
> +const auditoriumsNames = auditoriumsConfig.map((el) => el.name)
лучше бы просто массив написал, а если тест надо то через джест

2022-12-08 15:23 UTC, Konstaphy commented on src/shared/ordinarySearch/ordinarySearch.tsx
> +          value={inputValue}
в пропсы

2022-12-08 17:29 UTC, OvechkinDmitry commented on src/shared/ordinarySearch/ordinarySearch.tsx
> +  {
для теста я имел ввиду какие данные должны показываться в выпадающем списке автокомплита , в принципе 
можно удалить и массив с названиями аудиторий поставить

2022-12-08 17:29 UTC, OvechkinDmitry commented on src/shared/ordinarySearch/ordinarySearch.tsx
> +const auditoriumsNames = auditoriumsConfig.map((el) => el.name)
для теста я имел ввиду какие данные должны показываться в выпадающем списке автокомплита , в принципе 
можно удалить и массив с названиями аудиторий поставить *

2022-12-10 19:21 UTC, Konstaphy approved these changes, later dismissed

2022-12-10 23:19 UTC, Konstaphy submitted a review, later dismissed

2022-12-10 23:31 UTC, Konstaphy commented
Дима, давай в этом же пр еще компоненту выбора этажа добавить

2022-12-11 19:37 UTC, Konstaphy requested changes

2022-12-11 19:37 UTC, Konstaphy commented on src/app/index.tsx
> +      <ChooseFloor links={["/", "/irit-rtf", "/link3", "/link4"]} size={64} />
давай не линками а колбеками, на одну нажимаешь одна функция выполняется, второе - вторая

2022-12-11 19:37 UTC, Konstaphy commented on src/shared/ chooseFloor/chooseFloor.tsx
> +            : "floor"
лучше вынести в юзМемо

2022-12-11 19:37 UTC, Konstaphy commented on src/shared/ chooseFloor/chooseFloor.tsx
> +  const floors = links.map((floor, index) => {
все в useMemo

2022-12-11 20:40 UTC, Konstaphy approved these changes
заебок

2022-12-11 21:14 UTC, OvechkinDmitry commented
> заебок

Заебок

2022-12-21 16:05 UTC, merged