Основное меню
quorus-environment/urfu-navigation pull request #7
Opened 2022-10-04 20:50 UTC by lenaa1

Добавила header, поправила роутинг, добавила основную страницу и разделила на карту и институты

2022-10-04 20:55 UTC, Konstaphy requested changes
умничка но исправь

2022-10-04 20:55 UTC, Konstaphy commented on src/app/index.tsx
> + * todo: менюшка
убрать, сделано же уже

2022-10-04 20:55 UTC, Konstaphy commented on src/index.css
> +
лишняя строчка

2022-10-04 20:55 UTC, Konstaphy commented on src/pages/main/main.tsx
> +      <img className='map' src={Map} alt='' />
"main__map"

2022-10-04 20:55 UTC, Konstaphy commented on src/pages/main/main.tsx
> +      <img className='map' src={Map} alt='' />
и альтернативный текст добавь пж

2022-10-04 20:55 UTC, Konstaphy commented on src/pages/main/main.tsx
> +        <div className='institutes'>
"main__institutes"

2022-10-04 20:55 UTC, Konstaphy commented on src/shared/ui/institute-logo/institute-logo.tsx
> +
Можешь добавить документацию (спроси потом у меня) что это за компонента и как ее использовать

2022-10-04 20:55 UTC, Konstaphy commented on src/widgets/header/ui/header.css
> +    background-color: #F4F4F2;
можно в переменную css вынести тоже крутая тема

2022-10-04 20:55 UTC, Konstaphy commented on src/widgets/header/ui/header.css
> +}
у тебя по стандарту и так font-weight 400

2022-10-04 20:55 UTC, Konstaphy commented on svg.d.ts
> +}
это скорее чтобы я не забыл: сделать через регулярку все типы изображений

2022-10-04 20:56 UTC, Konstaphy commented on src/widgets/header/ui/header.css
> +    background-color: #F4F4F2;
2 раза встречается в одном файле

2022-10-04 21:14 UTC, Konstaphy approved these changes
збс

2022-10-05 11:52 UTC, OvechkinDmitry commented on svg.d.ts
> +declare module '*.svg' {
для чего это нужно?

2022-10-05 11:52 UTC, OvechkinDmitry approved these changes

2022-10-05 11:58 UTC, Konstaphy commented on svg.d.ts
> +declare module '*.svg' {
В общем - компилятор тски без этого не знает как компилировать файлы когда мы пишем import Logo from "./logo.jpeg", в этом файле мы указваем ему что такие штуки нужно компилировать в строку(в ссылку на файл)

2022-10-05 12:11 UTC, merged

2022-10-05 19:05 UTC, OvechkinDmitry commented on svg.d.ts
> +declare module '*.svg' {
ок!