Создал стартовые иконки
quorus-environment/urfu-navigation pull request #8
Opened 2022-10-05 14:53 UTC by OvechkinDmitry

2022-10-05 14:58 UTC, Konstaphy requested changes
в целом заебок, только линтер надо подрубить на onSave (хз как в вс коде это сделать, загугли)

2022-10-05 14:58 UTC, Konstaphy commented on src/shared/ui/Exit/Exit.tsx
> +}
напиши в консоли eslint --fix, у тебя линтер не работает

2022-10-05 14:58 UTC, Konstaphy commented on src/shared/ui/MenuToggle/MenuToggle.tsx
> +export const MenuToggle: FC<MenuToggleProps> = ({color = '#9D9B98', size = 16,}) => {
цвет лучше вынести в shared/constants.ts и экспортировать оттуда

2022-10-05 14:58 UTC, Konstaphy commented on src/shared/ui/RoundButton/RoundButton.tsx
> +           <div className="inner" style={{width:size&&size/1.5,height:size&&size/1.5,backgroundColor: color}}></div>
вычисление сайза лучше вынести в отдельную константу и замемоизировать (useMemo)

2022-10-05 14:58 UTC, Konstaphy commented on tsconfig.json
> +    "jsx": "preserve"
а это что делает?

2022-10-05 15:02 UTC, OvechkinDmitry commented on tsconfig.json
> +    "jsx": "preserve"
не знаю установилось так видимо

2022-10-06 18:54 UTC, Konstaphy commented on src/app/index.tsx
> +        <Route path='/' element={<Main />} />
исправь линтером

2022-10-06 18:55 UTC, Konstaphy approved these changes
Заебок но поправь там одиночные кавычки

2022-10-06 18:55 UTC, Konstaphy commented on src/app/index.tsx
> +        <Route path='/' element={<Main />} />
eslint --fix

2022-10-06 19:12 UTC, Konstaphy approved these changes

2022-10-06 19:21 UTC, merged